---
- name: Ensure Vault prerequisite packages are installed
  ansible.builtin.package:
    name: "{{ vault_install_prerequisites }}"
    state: present

- name: Ensure the custom facts directory exists
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: "directory"
    owner: root
    group: root
    mode: "0755"

- name: Assign the Vault architecture
  ansible.builtin.set_fact:
    _vault_architecture: >-
      {{ vault_install_architecture_map[ansible_architecture] }}

- name: Ensure the Vault binary is present
  ansible.builtin.unarchive:
    src: "{{ vault_install_download_url }}"
    dest: "{{ vault_install_destination }}"
    remote_src: true
    owner: root
    group: root
    mode: '0775'
