---
include:
  - project: 'dubzland/ci-templates'
    file: 'ansible-collection.yml'

variables:
  DUBZLAND_COLLECTION_NAME: vault

lint:
  extends: .ansible:lint

sanity:
  extends: .ansible:sanity

sanity-release:
  extends: .ansible:sanity-release

unit:
  extends: .ansible:unit

coverage:
  extends: .ansible:coverage
  needs:
    - unit

unit-release:
  extends: .ansible:unit-release

molecule:
  extends: .ansible:molecule

molecule-release:
  extends: .ansible:molecule-release

docs:
  extends: .ansible-collection:docs

build:
  extends: .ansible-collection:build

release:
  extends: .ansible-collection:release

galaxy:
  extends: .ansible-collection:galaxy

release-docs:
  extends: .ansible-collection:release-docs
