---
namespace: dubzland
name: vault
version: "1.0.0"
readme: README.md
authors:
  - Josh Williams <jdubz@dubzland.com>
description: Installs and configures the HashiCorp Vault secret server.
license:
  - MIT
tags:
  - linux
  - debian
  - ubuntu
  - vault

dependencies:
  "community.general": "*"
  "dubzland.utils": "*"

repository: https://git.dubzland.com/dubzland/ansible-collection-vault

# The URL to any online docs
documentation: |
  https://docs.dubzland.io/ansible-collections/collections/dubzland/vault/

# The URL to the homepage of the collection/project
homepage: https://git.dubzland.com/dubzland/ansible-collection-vault

# The URL to the collection issue tracker
issues: https://git.dubzland.com/dubzland/ansible-collection-vault/-/issues
build_ignore:
  - .ansible-lint
  - .cache
  - .gitignore
  - .gitlab-ci.yml
  - .venv
  - .yamllint
  - requirements-*.txt
  - extensions
