---
argument_specs:
  main:
    short_description: >-
      Installs the L(HashiCorp Vault,https://www.hashicorp.com/products/vault)
      binary.
    description:
      - Downloads the Vault server binary (B(vault)).
      - Creates a system user and group for running the B(vault) service.
      - Adds a systemd unit for managing the B(vault) service.
      - Creates a minimal B(vault) configuration.
    options:
      vault_install_version:
        type: str
        default: "1.16.0"
        description: Version of Vault to be installed.
