---
- name: Converge
  hosts: all
  roles:
    - role: dubzland.vault.vault_install
    - role: dubzland.vault.vault_server
    - role: dubzland.vault.vault_init
    - role: dubzland.vault.vault_unseal
