---
- name: Retrieve the current unseal status
  ansible.builtin.include_tasks: status.yml

- name: Try and unseal Vault
  ansible.builtin.include_tasks: unseal.yml
  vars:
    _unseal_index: "{{ item }}"
  when: _vault_sealed
  loop: "{{ range(0, _vault_total_shares | int) | list }}"
