---
- name: Assign the unseal key file
  ansible.builtin.set_fact:
    _unseal_key_file: "{{ vault_unseal_tokens_directory }}/unseal/key_{{ _unseal_index }}"
  when: _vault_sealed

- name: Unseal Vault with unseal keys
  ansible.builtin.command:
    cmd: "vault operator unseal {{ lookup('file', _unseal_key_file) }}"
  environment:
    VAULT_ADDR: "{{ vault_unseal_addr }}"
  when: _vault_sealed

- name: Retrieve the current unseal status
  ansible.builtin.include_tasks: status.yml
  when: _vault_sealed
