---
galaxy_info:
  role_name: vault_init
  author: dubzland
  description: Initializes a HashiCorp Vault installation.
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
    - name: Ubuntu
      versions:
        - jammy
        - focal
  galaxy_tags:
    - vault
    - hashicorp
    - secrets
    - linux
    - debian
    - ubuntu

dependencies: []
